# Generated by Django 3.1.2 on 2020-10-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_header', models.CharField(blank=True, max_length=100, null=True)),
                ('intro_text', models.TextField(blank=True, max_length=10000, null=True)),
                ('intro_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='about/')),
                ('intro_img_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('reviews_info_header', models.CharField(blank=True, max_length=100, null=True)),
                ('reviews_info_text', models.TextField(blank=True, max_length=10000, null=True)),
                ('reviews_info_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='about/')),
                ('reviews_info_img_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('score_info_header', models.CharField(blank=True, max_length=100, null=True)),
                ('score_info_text', models.TextField(blank=True, max_length=10000, null=True)),
                ('score_info_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='about/')),
                ('score_info_img_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('game_info_header', models.CharField(blank=True, max_length=100, null=True)),
                ('game_info_text', models.TextField(blank=True, max_length=10000, null=True)),
                ('game_info_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='about/')),
                ('game_info_img_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('users_info_header', models.CharField(blank=True, max_length=100, null=True)),
                ('users_info_text', models.TextField(blank=True, max_length=10000, null=True)),
                ('users_info_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='about/')),
                ('users_info_img_alt', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
