# Generated by Django 3.1.2 on 2020-10-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='intro_slogan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
