# Generated by Django 3.1 on 2020-08-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200810_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('site_short_name', models.CharField(max_length=50)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('logo_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='stores/logo_images/')),
                ('show_logo_img', models.BooleanField(default=False)),
                ('logo_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('show_logo_icon', models.BooleanField(default=False)),
            ],
        ),
    ]
