# Generated by Django 3.1 on 2020-08-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_misc_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='misc_tags',
        ),
        migrations.AddField(
            model_name='review',
            name='misc_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.reviewsite'),
        ),
    ]
