# Generated by Django 3.1 on 2020-08-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20200810_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='long_quote',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='short_quote',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
