# Generated by Django 3.1 on 2020-08-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20200810_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
