# Generated by Django 3.1 on 2020-08-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20200810_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='max_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
