# Generated by Django 3.1.2 on 2020-10-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('web_url', models.URLField(blank=True, null=True)),
                ('logo_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='developers/logo_images/')),
                ('show_logo_img', models.BooleanField(default=False)),
                ('logo_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('show_logo_icon', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GenreTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=40, null=True)),
                ('show_name', models.BooleanField(blank=True, default=True, null=True)),
                ('is_important', models.BooleanField(blank=True, default=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('show_icon', models.BooleanField(default=False)),
                ('tag_category', models.CharField(default='genre', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MiscTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=40, null=True)),
                ('show_name', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('show_icon', models.BooleanField(default=False)),
                ('tag_category', models.CharField(default='misc', max_length=40)),
                ('tag_sub_category', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pegi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pegi_class', models.CharField(max_length=10)),
                ('short_name', models.CharField(blank=True, max_length=10, null=True)),
                ('pegi_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='pegi/pegi_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=40)),
                ('short_name', models.CharField(max_length=10)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('show_icon', models.BooleanField(default=True)),
                ('img', models.ImageField(blank=True, max_length=255, null=True, upload_to='platforms/platform_images/')),
                ('show_img', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('web_url', models.URLField(blank=True, null=True)),
                ('logo_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='publishers/logo_images/')),
                ('show_logo_img', models.BooleanField(default=False)),
                ('logo_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('show_logo_icon', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('web_url', models.URLField(blank=True, null=True)),
                ('logo_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='stores/logo_images/')),
                ('show_logo_img', models.BooleanField(default=False)),
                ('logo_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('show_logo_icon', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=40, null=True)),
                ('show_name', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('show_icon', models.BooleanField(default=False)),
                ('tag_category', models.CharField(default='theme', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('thumb_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='games/thumb_images/')),
                ('large_cover_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='games/cover_images/')),
                ('in_game_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='games/ingame_images/')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('description_src', models.CharField(blank=True, max_length=40, null=True)),
                ('description_src_url', models.URLField(blank=True, max_length=255, null=True)),
                ('avg_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.developer')),
                ('genre_tags', models.ManyToManyField(blank=True, to='games.GenreTag')),
                ('misc_tags', models.ManyToManyField(blank=True, to='games.MiscTag')),
                ('pegi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.pegi')),
                ('platforms', models.ManyToManyField(blank=True, to='games.Platform')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.publisher')),
                ('stores', models.ManyToManyField(blank=True, to='games.Store')),
                ('theme_tags', models.ManyToManyField(blank=True, to='games.ThemeTag')),
            ],
        ),
    ]
