# Generated by Django 3.1 on 2020-08-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_tag_tagcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='tag_name',
        ),
    ]
