# Generated by Django 3.1 on 2020-08-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200804_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(to='games.Tag'),
        ),
    ]
