# Generated by Django 3.1 on 2020-08-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pegi_class', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=40)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='description_src',
            field=models.URLField(default='http//www.google.com'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='pegi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.pegi'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='games.Platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.publisher'),
        ),
        migrations.AddField(
            model_name='game',
            name='stores',
            field=models.ManyToManyField(to='games.Store'),
        ),
    ]
