# Generated by Django 3.1 on 2020-08-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20200806_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_icon',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_category',
            field=models.CharField(default='genre', max_length=40),
        ),
    ]
