# Generated by Django 3.1 on 2020-08-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20200806_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=40, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('show_icon', models.BooleanField(default=False)),
                ('tag_category', models.CharField(default='genre', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MiscTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=40, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('show_icon', models.BooleanField(default=False)),
                ('tag_category', models.CharField(default='misc', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=40, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('show_icon', models.BooleanField(default=False)),
                ('tag_category', models.CharField(default='theme', max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='company_name',
            new_name='long_name',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='company_name',
            new_name='long_name',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_name',
            new_name='long_name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tags',
        ),
        migrations.AddField(
            model_name='developer',
            name='logo_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='logo_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='developers/logo_images/'),
        ),
        migrations.AddField(
            model_name='developer',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='show_logo_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='show_logo_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='web_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='description_src_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='thumb_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='games/thumb_images/'),
        ),
        migrations.AddField(
            model_name='pegi',
            name='pegi_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pegi/pegi_images/'),
        ),
        migrations.AddField(
            model_name='pegi',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='platforms/platform_images/'),
        ),
        migrations.AddField(
            model_name='platform',
            name='show_icon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='show_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='logo_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='logo_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='publishers/logo_images/'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='show_logo_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='show_logo_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='web_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='stores/logo_images/'),
        ),
        migrations.AddField(
            model_name='store',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='show_logo_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='show_logo_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='web_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='description_src',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.developer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pegi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.pegi'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.publisher'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagCategory',
        ),
        migrations.AddField(
            model_name='game',
            name='genre_tags',
            field=models.ManyToManyField(to='games.GenreTag'),
        ),
        migrations.AddField(
            model_name='game',
            name='misc_tags',
            field=models.ManyToManyField(to='games.MiscTag'),
        ),
        migrations.AddField(
            model_name='game',
            name='theme_tags',
            field=models.ManyToManyField(to='games.ThemeTag'),
        ),
    ]
