# Generated by Django 3.1 on 2020-08-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20200806_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='tags',
            new_name='genre_tags',
        ),
    ]
