# Generated by Django 3.1 on 2020-08-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20200807_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='genretag',
            name='show_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='misctag',
            name='show_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themetag',
            name='show_name',
            field=models.BooleanField(default=True),
        ),
    ]
