# Generated by Django 3.1 on 2020-08-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20200806_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=40)),
                ('tag_icon', models.CharField(blank=True, max_length=40, null=True)),
                ('tag_category', models.CharField(default='genre', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='genre_tags',
            field=models.ManyToManyField(to='games.GenreTag'),
        ),
    ]
