# Generated by Django 3.1 on 2020-08-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20200808_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='avg_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
