# Generated by Django 3.1 on 2020-08-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_game_avg_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='in_game_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='games/thumb_images/'),
        ),
        migrations.AddField(
            model_name='game',
            name='large_cover_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='games/thumb_images/'),
        ),
    ]
