# Generated by Django 3.1 on 2020-08-06 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20200806_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=40)),
                ('tag_icon', models.CharField(blank=True, max_length=40, null=True)),
                ('tag_category', models.CharField(default='misc', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=40)),
                ('tag_icon', models.CharField(blank=True, max_length=40, null=True)),
                ('tag_category', models.CharField(default='theme', max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
