# Generated by Django 3.1 on 2020-08-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20200819_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='in_game_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='games/ingame_images/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='large_cover_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='games/cover_images/'),
        ),
    ]
