# Generated by Django 3.1 on 2020-08-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20200806_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='misc_tags',
            field=models.ManyToManyField(null=True, to='games.MiscTag'),
        ),
        migrations.AddField(
            model_name='game',
            name='theme_tags',
            field=models.ManyToManyField(null=True, to='games.ThemeTag'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre_tags',
            field=models.ManyToManyField(null=True, to='games.GenreTag'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(null=True, to='games.Platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stores',
            field=models.ManyToManyField(null=True, to='games.Store'),
        ),
    ]
