# Generated by Django 3.1 on 2020-08-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20200819_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='misctag',
            name='tag_sub_category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre_tags',
            field=models.ManyToManyField(blank=True, to='games.GenreTag'),
        ),
        migrations.AlterField(
            model_name='game',
            name='misc_tags',
            field=models.ManyToManyField(blank=True, to='games.MiscTag'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='games.Platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stores',
            field=models.ManyToManyField(blank=True, to='games.Store'),
        ),
        migrations.AlterField(
            model_name='game',
            name='theme_tags',
            field=models.ManyToManyField(blank=True, to='games.ThemeTag'),
        ),
    ]
