# Generated by Django 3.1 on 2020-08-06 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20200806_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumb_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='game_thumbs'),
            preserve_default=False,
        ),
    ]
