# Generated by Django 3.1 on 2020-08-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_game_thumb_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genretag',
            old_name='tag_name',
            new_name='long_name',
        ),
        migrations.RenameField(
            model_name='misctag',
            old_name='tag_name',
            new_name='long_name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='long_name',
        ),
        migrations.RenameField(
            model_name='themetag',
            old_name='tag_name',
            new_name='long_name',
        ),
        migrations.AddField(
            model_name='genretag',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='misctag',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='themetag',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='misctag',
            name='tag_category',
            field=models.CharField(default='theme', max_length=40),
        ),
    ]
