# Generated by Django 3.1 on 2020-08-06 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20200806_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='company_short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='company_url',
            field=models.URLField(default='http//www.google.com'),
        ),
        migrations.AddField(
            model_name='pegi',
            name='thumb_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pegi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='company_short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='company_url',
            field=models.URLField(default='http//www.google.com'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_icon',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_url',
            field=models.URLField(default='http//www.google.com'),
        ),
    ]
