# Generated by Django 3.1 on 2020-08-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_platform_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagCategory',
        ),
    ]
