# Generated by Django 3.1 on 2020-08-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_auto_20200806_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thumb_img',
            field=models.ImageField(upload_to='game_thumbs/'),
        ),
    ]
