# Generated by Django 3.1 on 2020-08-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_auto_20200806_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='company_short_name',
            new_name='short_name',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='company_short_name',
            new_name='short_name',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_short_name',
            new_name='short_name',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='company_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description_src',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='company_url',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_icon',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_url',
        ),
        migrations.AddField(
            model_name='developer',
            name='logo_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='developers/logotypes/'),
        ),
        migrations.AddField(
            model_name='developer',
            name='show_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='show_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='description_src_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='description_src_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genretag',
            name='show_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='misctag',
            name='show_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='logo_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='platforms/logotypes/'),
        ),
        migrations.AddField(
            model_name='platform',
            name='show_icon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='show_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='logo_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='publishers/logotypes/'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='show_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='show_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='stores/logotypes/'),
        ),
        migrations.AddField(
            model_name='store',
            name='show_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='show_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='themetag',
            name='show_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.developer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre_tags',
            field=models.ManyToManyField(blank=True, to='games.GenreTag'),
        ),
        migrations.AlterField(
            model_name='game',
            name='misc_tags',
            field=models.ManyToManyField(blank=True, to='games.MiscTag'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pegi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.pegi'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='games.Platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.publisher'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='stores',
            field=models.ManyToManyField(blank=True, to='games.Store'),
        ),
        migrations.AlterField(
            model_name='game',
            name='theme_tags',
            field=models.ManyToManyField(blank=True, to='games.ThemeTag'),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumb_img',
            field=models.ImageField(blank=True, null=True, upload_to='game_thumbs/'),
        ),
        migrations.AlterField(
            model_name='misctag',
            name='tag_category',
            field=models.CharField(default='misc', max_length=40),
        ),
    ]
