# Generated by Django 3.1 on 2020-08-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_auto_20200807_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='show_icon',
            field=models.BooleanField(default=False),
        ),
    ]
