# Generated by Django 3.1 on 2020-08-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_game_show_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='show_icon',
            new_name='show_img',
        ),
    ]
