# Generated by Django 3.1 on 2020-08-25 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200825_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommentsscore',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercommentsscore',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
