# Generated by Django 3.1 on 2020-08-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200825_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommentsscore',
            name='comment',
            field=models.TextField(default='none', max_length=300),
        ),
    ]
