# Generated by Django 3.1 on 2020-08-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200827_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommentsscore',
            name='comment',
            field=models.TextField(default='', max_length=300),
        ),
    ]
